global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200'] 